#!/usr/bin/env sh

distro=$(if echo " bullseye focal impish jammy uma una " | grep -q " $(lsb_release -sc) "; then echo $(lsb_release -sc); else echo focal; fi)

echo "deb [arch=amd64] http://deb.librewolf.net $distro main" | tee /etc/apt/sources.list.d/librewolf.list

wget https://deb.librewolf.net/keyring.gpg -O /etc/apt/trusted.gpg.d/librewolf.gpg

apt update && apt install librewolf -y
