#!/usr/bin/env sh

apt install libncursesw5-dev libdbus-1-dev libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev


cd /gallifrey/repos
git clone https://github.com/hrkfdn/ncspot && cd ncspot

cargo build --release --features cover

cp target/release/ncspot /usr/local/bin
